/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.karmazyn' at '1/26/15 8:25 PM' with Gradle 2.2.1
 *
 * @author m.karmazyn, @date 1/26/15 8:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
