/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.karmazyn' at '2/18/15 9:17 PM' with Gradle 2.3
 *
 * @author m.karmazyn, @date 2/18/15 9:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
