/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.karmazyn' at '3/4/15 9:42 PM' with Gradle 2.3
 *
 * @author m.karmazyn, @date 3/4/15 9:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
