/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'm.karmazyn' at '2/11/15 11:34 PM' with Gradle 2.2.1
 *
 * @author m.karmazyn, @date 2/11/15 11:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
